spring.application.name=upload-practice

#s3
cloud.aws.s3.bucket=cherry-s3
cloud.aws.stack.auto=false
cloud.aws.region.static=ap-southeast-2
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}